### ISSUE TITLE
Generate button not working for me

### ISSUE THREAD

**Issue by Nacurutu** [AUTOMATIC1111/stable-diffusion-webui-promptgen#1]
Hi, thank you for the extension.

I have downloaded the extension and also the model from hugging, the model is already in the model's folder of the extension.

I selected the same parameters as the example image shows, wrote the first words of the prompt, click generate and nothing happens.

![image](https://user-images.githubusercontent.com/18109442/213147369-c72ef27a-5ee7-4c7a-8ea9-57c04adff3c1.png)

![image](https://user-images.githubusercontent.com/18109442/213147867-b2bc7d40-8539-4f08-a08f-306f0f21c8f6.png)

I have selected the 2 options on the model list, but still nothing.

EDIT: Working now after restarting webUI 3 times.

![image](https://user-images.githubusercontent.com/18109442/213151818-02c113ec-be94-458c-9376-9cb0c10b23c5.png)

**Comment by DillonSimeone** [comment]
Aye, seeing this on my side too.

`Uncaught (in promise) ReferenceError: randomId is not defined` pops up in the console when clicking on generate. Hmm. Something went wrong with the svelte framework, it seems. 

`Uncaught (in promise) ReferenceError: randomId is not defined
    submit_promptgen (index):4201
    anonymous index.0b923826.js line 75 > AsyncFunction:3
    ac index.0b923826.js:34
    Nt index.0b923826.js:76
    ae index.0b923826.js:4
    ae index.0b923826.js:4
    _ Button.svelte:10
    ae index.0b923826.js:4
    ae index.0b923826.js:4
    B Button.svelte:9
    Z index.0b923826.js:1
    m Button.svelte:14
    ct index.0b923826.js:4
    m Button.svelte:14
    ct index.0b923826.js:4
    m index.0b923826.js:34
    ct index.0b923826.js:4
    m index.0b923826.js:34
    m index.0b923826.js:34
    m index.0b923826.js:34
    m Column.svelte:13
    ct index.0b923826.js:4
    m index.0b923826.js:34
    ct index.0b923826.js:4
    m index.0b923826.js:34
    m index.0b923826.js:34
    m index.0b923826.js:34
    m Row.svelte:10
    ct index.0b923826.js:4
    m index.0b923826.js:34
    ct index.0b923826.js:4
    m index.0b923826.js:34
    m index.0b923826.js:34
    m index.0b923826.js:34
    m TabItem.svelte:20
    m index.78dbca30.js:1
    m Column.svelte:13
    ct index.0b923826.js:4
    m TabItem.svelte:23
    ct index.0b923826.js:4
    m Tabs.svelte:9
    ct index.0b923826.js:4
    m index.0b923826.js:34
    ct index.0b923826.js:4
    m index.0b923826.js:34
    m index.0b923826.js:34
    m index.0b923826.js:34
    m index.0ed417a4.js:1
    m Tabs.svelte:49
    ct index.0b923826.js:4
    m index.0ed417a4.js:1
    ct index.0b923826.js:4
    m index.0b923826.js:34
    ct index.0b923826.js:4
    m index.0b923826.js:34
    m index.0b923826.js:34
    m index.0b923826.js:34
    m Column.svelte:13
    ct index.0b923826.js:4
    m index.0b923826.js:34
    ct index.0b923826.js:4
    m index.0b923826.js:74
    p index.0b923826.js:75
    Rl index.0b923826.js:4
    mt index.0b923826.js:4
    promise callback*so index.0b923826.js:4
    zl index.0b923826.js:4
    ctx index.0b923826.js:4
    xc index.0b923826.js:76
    promise callback*xc/< index.0b923826.js:76
    promise callback*xc index.0b923826.js:76
    Tt index.0b923826.js:4
    kc index.0b923826.js:76
    ml index.0b923826.js:77
    connectedCallback index.0b923826.js:77
    w0 index.0b923826.js:77
    <anonymous> index.0b923826.js:77
`

**Comment by Rogal80** [comment]
for me it doesn't work even after 5 restarts :(

Firefox, Windows
--xformers --api --listen --enable-insecure-extension-access

**Comment by Nacurutu** [comment]
Auto updated the extension today, give it a try, also, try to download the model he mention on the repo and copy it to the models folder on the extension...

**Comment by Piotr-Suli** [comment]
I couldn't find any definition of function `randomId` either.
And no amount of restart helped (there was nothing to update)
As temporary fix You can paste this into browser console:
```
function randomId(){
    return Math.floor(Math.random()*10000000000)
}
```

**Comment by DillonSimeone** [comment]
Yeah, with the new update, it works now. This issue can be closed.

**Comment by Leka1B** [comment]
Installed it today and got the same issue, the console doesn't show any signs of life too
Upd: Updating the webui fixed it for me, guess I need to be more patient at launch
